version: "3"
services:
  goawd:
    build: .
    restart: always
    ports:
      - "1337:1337"
      - "8023:8023"
    volumes:
      - goawd-data:/data
      - ./plugins:/app/plugins
    command: ["-storage", "file", "-file-path", "/data/goawd.json", "-public", "./public"]

volumes:
  goawd-data: